# Development Environment Configuration

server:
  mode: "debug"
  port: 8080

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "seckill_dev"
  log_level: "info"

redis:
  host: "localhost"
  port: 6379
  db: 0

etcd:
  endpoints:
    - "localhost:2379"

log:
  level: "debug"
  format: "console"
  output: "stdout"

metrics:
  enabled: true
  port: 9090

tracing:
  enabled: true
  jaeger:
    endpoint: "http://localhost:14268/api/traces"
    service_name: "seckill-api-dev"

rate_limit:
  enabled: true
  global:
    rps: 1000
    burst: 2000
    ttl: 60s
  per_user:
    rps: 50
    burst: 100
    ttl: 60s
  per_ip:
    rps: 200
    burst: 400
    ttl: 60s

circuit_break:
  enabled: true
  max_requests: 100
  interval: 60s
  timeout: 30s
  failure_ratio: 0.6
  min_request_count: 10

security:
  jwt:
    secret: "dev-secret-key-not-for-production"
    expiration: 24h
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
      - "http://127.0.0.1:3000"
      - "http://127.0.0.1:8080"