# Test Environment Configuration

server:
  mode: "test"
  port: 8081

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "seckill_test"
  max_idle_conns: 5
  max_open_conns: 10
  log_level: "warn"

redis:
  host: "localhost"
  port: 6379
  db: 15  # Use different database for tests
  pool_size: 5

etcd:
  endpoints:
    - "localhost:2379"

logging:
  level: "warn"
  format: "console"
  output: "stdout"
  caller: false
  stack_trace: false

metrics:
  enabled: false

tracing:
  enabled: false

rate_limit:
  enabled: false

circuit_breaker:
  enabled: false

security:
  jwt:
    secret: "test-secret-key"
    expiration: 1h
  cors:
    allowed_origins:
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
    allow_credentials: true

seckill:
  inventory:
    cache_expiration: 60s
  order:
    timeout: 300s  # 5 minutes for tests
  activity:
    cache_expiration: 60s
    pre_load_time: 30s