# Seckill System Configuration
# Default configuration for development environment

server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576  # 1MB

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  dbname: "seckill"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s
  conn_max_idle_time: 1800s
  log_level: "info"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

etcd:
  endpoints:
    - "localhost:2379"
  dial_timeout: 5s
  request_timeout: 10s
  username: ""
  password: ""

queue:
  driver: "memory"  # memory, redis, nats
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 1
  nats:
    url: "nats://localhost:4222"
    cluster_id: "seckill-cluster"
    client_id: "seckill-client"

log:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output: "stdout"  # stdout, stderr, file
  filename: "./logs/app.log"
  max_size: 100  # MB
  max_backups: 10
  max_age: 30  # days
  compress: true

metrics:
  enabled: true
  path: "/metrics"
  port: 9090
  namespace: "seckill"
  subsystem: "api"

tracing:
  enabled: true
  jaeger:
    endpoint: "http://localhost:14268/api/traces"
    service_name: "seckill-api"
    sampler_type: "const"
    sampler_param: 1.0

rate_limit:
  enabled: true
  requests_per_second: 1000
  burst: 2000
  cleanup_interval: 60s

circuit_break:
  enabled: true
  max_requests: 100
  interval: 60s
  timeout: 30s
  failure_ratio: 0.6

cache:
  default_expiration: 300s  # 5 minutes
  cleanup_interval: 600s    # 10 minutes
  max_size: 10000

security:
  jwt:
    secret: "your-secret-key-change-in-production"
    issuer: "seckill-system"
    expire: 24h
    refresh_ttl: 168h  # 7 days
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Authorization"
      - "X-Requested-With"
    exposed_headers:
      - "Content-Length"
    allow_credentials: true
    max_age: 86400  # 24 hours

seckill:
  inventory:
    cache_prefix: "seckill:inventory:"
    cache_expiration: 300s
    batch_size: 100
  order:
    timeout: 900s  # 15 minutes
    cache_prefix: "seckill:order:"
  user:
    max_orders_per_activity: 1
    cache_prefix: "seckill:user:"
  activity:
    cache_prefix: "seckill:activity:"
    cache_expiration: 600s
    pre_load_time: 300s  # 5 minutes before start